---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: deinonyxus
# description will be included in the image's metadata
description: Bluefin DX with Nix and sprinkles.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: os-release
    properties:
      ID: deinonyxus
      NAME: Deinonyxus
      DEFAULT_HOSTNAME: deinonyxus
      HOME_URL: https://codeberg.org/randogoth/deinonyxus
      SUPPORT_URL: https://codeberg.org/randogoth/deinonyxus/issues
      BUG_REPORT_URL: https://codeberg.org/randogoth/deinonyxus/issues

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - os-release-pretty.sh
      - ensure-labwc-autostart.sh

  - type: script
    scripts:
      - install-lix.sh

  - type: systemd
    system:
      enabled:
        - nix-overlay.service
        - nix-daemon.service
        - nix-daemon.socket
    user:
      enabled:
        - labwc-menu-update.path
        - labwc-themerc-update.path
        - dms-gtk-theme.path
        - dms.path
        - dms-settings-seed.service
        - dsearch.service

  - type: dnf
    repos:
      copr:
        enable:
          - avengemedia/dms
      files:
        add:
          - https://repo.vscodium.dev/vscodium.repo
          - https://negativo17.org/repos/fedora-uld.repo
    install:
      packages:
        - repo: vscodium
          packages:
          - codium
        - repo: fedora-uld
          packages: 
          - uld
        - dgop
        - dms
        - dsearch
        - ghostty
        - gnome-online-accounts-gtk
        - grim
        - khal
        - labwc
        - labwc-menu-generator
        - loginctl
        - papirus-icon-theme
        - syncthing
        - thunar
        - uv
        - waydroid
        - wayland-utils
        - xdg-desktop-portal-wlr
    remove:
      packages:
        - android-tools
        - cockpit-bridge
        - cockpit-machines
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-podman
        - cockpit-selinux
        - cockpit-storaged
        - cockpit-system
        - code
        - docker-ce
        - docker-ce-cli
        - docker-ce-rootless-extras
        - docker-compose-plugin
        - docker-model-plugin

  - type: gnome-extensions
    uninstall:
      - Dash to Dock
      - GSConnect
      - Launch New Instance
      - Search Light
    install:
      - Alphabetical App Grid
      - Hide Top Bar 

  - type: justfiles
    include:
      - papirus.just
      - nixpkgs.just
      - ghostty.just

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - net.waterfox.waterfox
          - org.telegram.desktop
          - org.freedesktop.Platform.VulkanLayer.gamescope
        remove: # replace default Firefox with Waterfox
          - org.mozilla.firefox
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
