---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: deinonyxus
# description will be included in the image's metadata
description: Bluefin DX with Nix and sprinkles.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - install-lix.sh

  - type: systemd
    system:
      enabled:
        - nix-overlay.service
        - nix-daemon.service

  - type: dnf
    repos:
      files:
        add:
          - https://repo.vscodium.dev/vscodium.repo
    install:
      packages:
        - repo: vscodium
          packages:
          - codium
        - syncthing
        - uv
        - waydroid
    remove:
      packages:
        - android-tools
        - cockpit-bridge
        - cockpit-machines
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-podman
        - cockpit-selinux
        - cockpit-storaged
        - cockpit-system
        - code
        - docker-ce
        - docker-ce-cli
        - docker-ce-rootless-extras
        - docker-compose-plugin
        - docker-model-plugin

  - type: justfiles
    include:
      - nixpkgs.just

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
          - org.telegram.desktop
        remove: # replace default Firefox with Waterfox
          - org.mozilla.firefox
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
